### PR TITLE
Re-implement container functionality

### PR DESCRIPTION
**Pull request by Ryshackleton**
This PR re-implements the user-specified `container` element functionality, this time with the following "features":

- optionally specify the `container` as a css selector or a DOMElement
- Uses the `container` element's `top` to determine scroll direction when `pageYOffset` is constant, but falls back to using `pageYOffset` where possible
- checks for scrollable `container` elements and throws errors to indicate when direction calculations will fail
- when `container` is not specified, checks the DOM tree above the step elements for scrollable parent containers and throws errors when scrollable parent containers are found.

I added quite a few test cases in the form of html files to `dev/container-tests/`.  These outline a number of use cases where errors might be thrown and where scrollama should behave as expected.  Please let me know if you can think of other test cases or ways this functionality might affect other functionality that exists in scrollama.  I'm open to deleting these test files to avoid cluttering up the repo, but I found them useful for testing this functionality.

### CODE REVIEW

**Comment by russellgoldenberg** [comment]
Thanks for putting the time into this! I cloned your repo and started playing around with the demos. Admittedly there is a lot going on so I need to spend a bit more time reviewing. One thing I noticed is that the examples don't seem to produce a container that has its own scrollbar (which I think was part of the initial desire). I'll keep exploring though and let you know if I have other questions.

**Comment by Ryshackleton** [comment]
No problem. Glad to help! I fixed the issue you mentioned with scroll bars not showing up in the containers.  I had followed the example from the previous PR and used a height: view height, which worked on a small screen I was working on, but not on larger ones....the perils of using vh.

Unfortunately, I couldn't find a way to consistently determine scroll direction when the step container is scrollable, mainly due to the issue of determining which container is being scrolled at any given time. This is true whether a `container` element is specified or not (example 01-no-container-with-overflow-on-container-not-wrapper.html shows the no-container case).  What I tried to do was to outline some use cases where we can't accurately determine scroll direction and alert the user of those cases, which hopefully will be useful going forward.  Given that, I've come around to the idea that the container functionality might create more problems than it solves. 
 Maybe it's a good idea to keep the error checking and leave the container functionality out?  I'm open to whatever you think is best.

Also, if you have ideas about how to determine scroll position within a scrollable step container, I'm all ears!

**Comment by russellgoldenberg** [comment]
sorry for the long delay...

> Given that, I've come around to the idea that the container functionality might create more problems than it solves. Maybe it's a good idea to keep the error checking and leave the container functionality out? 

Would you be open to just doing a PR that does error checking but doesn't have the container functionality?

**Comment by Ryshackleton** [comment]
I'd be happy to! See #106.

I'm closing this PR now.

**Pull request closed without merging**
