### PR TITLE
Simplify converting DOM node lists to arrays

### PR DESCRIPTION
**Pull request by alexnoz**
Since we have the built-in `Array.from` method, I thought it is preferable to use it instead of a custom function.

### CODE REVIEW

**Comment by russellgoldenberg** [comment]
Thanks for the PR! But it looks like it needs a polyfill for browser support - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from

I'll just update to es6 syntax using destruction... eg. `[...parent.querySelectorAll(selector)];`

**Comment by alexnoz** [comment]
Yeah, you're right, I haven't seen this MDN reference :smiley:. I've tried the spread operator but it didn't work for some reason.

**Comment by russellgoldenberg** [comment]
Just tried it too, same. I'm using buble, not babel for es6 -> es5 transformation, so im guessing it just doesn't support it like babel does... I use it with babel fine [here](https://github.com/polygraph-cool/starter/blob/master/src/js/utils/dom.js#L9)

**Comment by alexnoz** [comment]
Found this [issue](https://github.com/rollup/rollup/issues/1623) in rollup's repo, hope this'll help.

**Pull request closed without merging**
